language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

jobs:
  include:
    - stage: npm release
      node_js: "stable"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          tags: true
